import type { NoahQuiz } from './types';

export const NOAH_QUIZZES: NoahQuiz[] = [
  {
    id: 1,
    question: '노아가 방주를 만든 나무는 무엇인가요?',
    options: ['소나무', '잣나무 (고페르 나무)', '떡갈나무', '올리브나무'],
    answer: 2,
    reference: '창세기 6:14',
  },
  {
    id: 2,
    question: '방주에 들어간 동물은 각각 몇 쌍씩 들어갔나요?',
    options: ['1쌍', '2쌍', '3쌍', '5쌍'],
    answer: 2,
    reference: '창세기 7:2',
  },
  {
    id: 3,
    question: '비가 며칠 동안 내렸나요?',
    options: ['7일', '20일', '40일', '100일'],
    answer: 3,
    reference: '창세기 7:12',
  },
  {
    id: 4,
    question: '노아가 방주에서 처음 보낸 새는?',
    options: ['비둘기', '까마귀', '참새', '독수리'],
    answer: 2,
    reference: '창세기 8:7',
  },
  {
    id: 5,
    question: '올리브 잎을 물고 돌아온 새는?',
    options: ['까마귀', '비둘기', '참새', '앵무새'],
    answer: 2,
    reference: '창세기 8:11',
  },
  {
    id: 6,
    question: '하나님이 다시는 홍수로 멸하지 않겠다는 약속의 표시는?',
    options: ['별', '무지개', '구름', '번개'],
    answer: 2,
    reference: '창세기 9:13',
  },
  {
    id: 7,
    question: '노아의 세 아들 이름이 아닌 것은?',
    options: ['셈', '함', '야벳', '아벨'],
    answer: 4,
    reference: '창세기 6:10',
  },
  {
    id: 8,
    question: '방주의 길이는 몇 규빗인가요?',
    options: ['100규빗', '200규빗', '300규빗', '400규빗'],
    answer: 3,
    reference: '창세기 6:15',
  },
  {
    id: 9,
    question: '방주는 몇 층으로 만들었나요?',
    options: ['1층', '2층', '3층', '4층'],
    answer: 3,
    reference: '창세기 6:16',
  },
  {
    id: 10,
    question: '노아의 홍수 이야기는 창세기 몇 장에 있나요?',
    options: ['1~3장', '4~5장', '6~9장', '10~12장'],
    answer: 3,
    reference: '창세기 6~9장',
  },
  {
    id: 11,
    question: '방주가 머문 산의 이름은?',
    options: ['시나이산', '아라랏산', '갈멜산', '호렙산'],
    answer: 2,
    reference: '창세기 8:4',
  },
  {
    id: 12,
    question: '노아의 나이가 홍수 때 몇 살이었나요?',
    options: ['500살', '600살', '700살', '800살'],
    answer: 2,
    reference: '창세기 7:6',
  },
  {
    id: 13,
    question: '방주의 너비는 몇 규빗인가요?',
    options: ['30규빗', '40규빗', '50규빗', '60규빗'],
    answer: 3,
    reference: '창세기 6:15',
  },
  {
    id: 14,
    question: '하나님이 노아에게 방주를 짓게 한 이유는?',
    options: ['여행을 위해', '세상이 악해져서', '바다를 건너려고', '보물을 숨기려고'],
    answer: 2,
    reference: '창세기 6:13',
  },
  {
    id: 15,
    question: '홍수 후 노아가 처음 한 일은?',
    options: ['집을 지었다', '제단을 쌓았다', '농사를 지었다', '나무를 심었다'],
    answer: 2,
    reference: '창세기 8:20',
  },
];
