import type { StageConfig } from './types';

export const STAGES: StageConfig[] = [
  {
    stage: 1,
    targetLines: 10,
    dropInterval: 1000,
    warningThreshold: 2.5,
    gameoverThreshold: 4.0,
    quizBlockCount: 2,
    verse: '하나님이 노아에게 이르시되 너는 방주를 지으라',
    verseRef: '창세기 6:14',
    rainIntensity: 1,
  },
  {
    stage: 2,
    targetLines: 15,
    dropInterval: 800,
    warningThreshold: 2.0,
    gameoverThreshold: 3.5,
    quizBlockCount: 3,
    verse: '노아가 모든 것을 하나님이 명하신 대로 행하였더라',
    verseRef: '창세기 6:22',
    rainIntensity: 2,
  },
  {
    stage: 3,
    targetLines: 20,
    dropInterval: 650,
    warningThreshold: 1.8,
    gameoverThreshold: 3.0,
    quizBlockCount: 4,
    verse: '여호와께서 그 뒤를 닫으시니라',
    verseRef: '창세기 7:16',
    rainIntensity: 3,
  },
  {
    stage: 4,
    targetLines: 25,
    dropInterval: 500,
    warningThreshold: 1.5,
    gameoverThreshold: 2.5,
    quizBlockCount: 5,
    verse: '물이 땅에서 줄어들기 시작하여',
    verseRef: '창세기 8:3',
    rainIntensity: 4,
  },
  {
    stage: 5,
    targetLines: 30,
    dropInterval: 400,
    warningThreshold: 1.2,
    gameoverThreshold: 2.0,
    quizBlockCount: 6,
    verse: '내가 무지개를 구름 속에 두었나니 이것이 나와 세상 사이의 언약의 증거니라',
    verseRef: '창세기 9:13',
    rainIntensity: 5,
  },
];
