import type { StageConfig } from './types';

export const STAGES: StageConfig[] = [
  {
    stage: 1,
    goliathHp: 6,
    attackInterval: 2500,
    attackPatterns: [1],
    obstacleSpeed: 2,
    weakPointOpenDuration: 3000,
    weakPointCloseDuration: 2000,
    prayerInterval: 8000,
    verse: '여호와는 나의 목자시니 내게 부족함이 없으리로다',
    verseRef: '시편 23:1',
  },
  {
    stage: 2,
    goliathHp: 10,
    attackInterval: 2000,
    attackPatterns: [1, 2],
    obstacleSpeed: 2.5,
    weakPointOpenDuration: 2500,
    weakPointCloseDuration: 2500,
    prayerInterval: 10000,
    verse: '네가 칼과 창과 단창으로 내게 나아오거니와 나는 만군의 여호와의 이름으로 네게 나아가노라',
    verseRef: '사무엘상 17:45',
  },
  {
    stage: 3,
    goliathHp: 14,
    attackInterval: 1800,
    attackPatterns: [1, 2, 3],
    obstacleSpeed: 3,
    weakPointOpenDuration: 2000,
    weakPointCloseDuration: 3000,
    prayerInterval: 12000,
    verse: '다윗이 블레셋 사람에게 이르되 너는 칼과 창과 단창으로 내게 나아오거니와',
    verseRef: '사무엘상 17:45',
  },
  {
    stage: 4,
    goliathHp: 18,
    attackInterval: 1500,
    attackPatterns: [1, 2, 3],
    obstacleSpeed: 3.5,
    weakPointOpenDuration: 1800,
    weakPointCloseDuration: 3500,
    prayerInterval: 14000,
    verse: '전쟁의 승패는 여호와께 있으므로 그가 너희를 우리 손에 넘기시리라',
    verseRef: '사무엘상 17:47',
  },
  {
    stage: 5,
    goliathHp: 24,
    attackInterval: 1200,
    attackPatterns: [1, 2, 3],
    obstacleSpeed: 4,
    weakPointOpenDuration: 1500,
    weakPointCloseDuration: 4000,
    prayerInterval: 16000,
    verse: '다윗이 블레셋 사람을 이기니라',
    verseRef: '사무엘상 17:50',
  },
];
