import type { StageConfig } from './types';

export const STAGES: StageConfig[] = [
  {
    stage: 1,
    targetCount: 15,
    lanes: 1,
    crowdSpeed: 0.5,
    spawnInterval: 2000,
    patience: 8000,
    hasFish: false,
    hasChild: false,
    hasComboRequest: false,
    verse: '예수께서 떡 다섯 개와 물고기 두 마리를 가지사 하늘을 우러러 축사하시고',
    verseRef: '마태복음 14:19',
    upgradeReward: 2,
  },
  {
    stage: 2,
    targetCount: 25,
    lanes: 1,
    crowdSpeed: 0.7,
    spawnInterval: 1800,
    patience: 7000,
    hasFish: true,
    hasChild: false,
    hasComboRequest: false,
    verse: '떼어 제자들에게 주시매 제자들이 무리에게 주니',
    verseRef: '마태복음 14:19',
    upgradeReward: 2,
  },
  {
    stage: 3,
    targetCount: 40,
    lanes: 2,
    crowdSpeed: 0.9,
    spawnInterval: 1500,
    patience: 6000,
    hasFish: true,
    hasChild: true,
    hasComboRequest: false,
    verse: '다 배불리 먹고 남은 조각을 열두 바구니에 차게 거두었으며',
    verseRef: '마태복음 14:20',
    upgradeReward: 3,
  },
  {
    stage: 4,
    targetCount: 60,
    lanes: 2,
    crowdSpeed: 1.1,
    spawnInterval: 1200,
    patience: 5500,
    hasFish: true,
    hasChild: true,
    hasComboRequest: true,
    verse: '먹은 사람은 여자와 아이 외에 오천 명이나 되었더라',
    verseRef: '마태복음 14:21',
    upgradeReward: 3,
  },
  {
    stage: 5,
    targetCount: 80,
    lanes: 3,
    crowdSpeed: 1.3,
    spawnInterval: 1000,
    patience: 5000,
    hasFish: true,
    hasChild: true,
    hasComboRequest: true,
    verse: '예수께서 이르시되 내가 곧 생명의 떡이니 내게 오는 자는 결코 주리지 아니할 것이요',
    verseRef: '요한복음 6:35',
    upgradeReward: 4,
  },
];
